excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://odmustafa.github.io
name: Omar Mustafa's Blog
description: My GitHub blog...
author: Omar Mustafa
avatar: http://www.gravatar.com/avatar/69b51472949ec7b6cddfcee0d0915d5a?s=120&d=mm&r=g
ga_domain: 
ga_tracking_id: 
theme: jekyll-theme-minimal